### ISSUE TITLE
qpdf not installed

### ISSUE THREAD

**Issue by dpasqualin** [sharelatex/clsi-sharelatex#27]
I was facing the following error and I fixed it by installing the package qpdf.
I'm running sharelatex on a debian 8 and this program is neither installed by default nor installed by texlive-full package. It might be good to add qpdf as a dependency in the wiki page https://github.com/sharelatex/sharelatex/wiki/Dependencies

```
[2015-05-27T19:48:52.975Z]  WARN: clsi/15135 on sharelatex: qpdf failed
    Error: spawn qpdf ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)
    --
    args: [
      "--linearize",
      "/home/sharelatex/sharelatex/data/compiles/5565cae1f83ff2115679dafd/output.pdf",
      "/home/sharelatex/sharelatex/data/compiles/5565cae1f83ff2115679dafd/.cache/clsi/14d96eb9c21/output.pdf.opt"
    ]
[2015-05-27T19:48:52.978Z]  WARN: clsi/15135 on sharelatex: qpdf returned error (code=-2)
    args: [
      "--linearize",
      "/home/sharelatex/sharelatex/data/compiles/5565cae1f83ff2115679dafd/output.pdf",
      "/home/sharelatex/sharelatex/data/compiles/5565cae1f83ff2115679dafd/.cache/clsi/14d96eb9c21/output.pdf.opt"
    ]
```

**Comment by henryoswald** [comment]
Thanks i've updated that now
