### ISSUE TITLE
Timeout received while compiling document

### ISSUE THREAD

**Issue by dpasqualin** [sharelatex/clsi-sharelatex#29]
Hi, I've been trying to compile a document in my instance of sharelatex but I receive a "Server Error" in the browser and a timeout on the server.

```
Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.
```

```
[2015-06-09T21:43:45.655Z] ERROR: clsi/28304 on sharelatex: error downloading url
    Error: ETIMEDOUT
        at null._onTimeout (/home/sharelatex/sharelatex/clsi/node_modules/request/index.js:599:15)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
    --
    url: http://localhost:3009/project/5577211e5fcc401c4dc09ea2/file/557721215fcc401c4dc09ea4
    --
    filePath: /home/sharelatex/sharelatex/data/cache/5577211e5fcc401c4dc09ea2:0136d84ba919fd155df44bea75ab062b
[2015-06-09T21:43:45.656Z] ERROR: clsi/28304 on sharelatex: error running compile (project_id=5577211e5fcc401c4dc09ea2)
    Error: ETIMEDOUT
        at null._onTimeout (/home/sharelatex/sharelatex/clsi/node_modules/request/index.js:599:15)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
[2015-06-09T21:43:45.661Z]  INFO: clsi/28304 on sharelatex: http request (response-time=61355, req.remote-addr=127.0.0.1, req.content-length=124480)
    POST /project/5577211e5fcc401c4dc09ea2/compile HTTP/1.1
[2015-06-09T21:43:45.663Z] ERROR: clsi/28304 on sharelatex: error downloading url
    Error: socket hang up
        at createHangUpError (http.js:1473:15)
        at Socket.socketCloseListener (http.js:1523:23)
        at Socket.emit (events.js:117:20)
        at TCP.close (net.js:466:12)
```

```
[2015-06-09T22:33:50.329Z] ERROR: web-sharelatex/28298 on sharelatex: CLSI returned failure code (project_id=5577211e5fcc401c4dc09ea2)
    Error: CLSI returned non-success code: 500
      at Request._callback (/home/sharelatex/sharelatex/web/app/js/Features/Compile/ClsiManager.js:88:19)
      at Request.self.callback (/home/sharelatex/sharelatex/web/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/sharelatex/sharelatex/web/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/sharelatex/sharelatex/web/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickDomainCallback (node.js:492:13)
    
[2015-06-09T22:33:50.330Z] ERROR: web-sharelatex/28298 on sharelatex: error passed to top level next middlewear (url=/project/5577211e5fcc401c4dc09ea2/compile, method=POST)
    Error: CLSI returned non-success code: 500
      at Request._callback (/home/sharelatex/sharelatex/web/app/js/Features/Compile/ClsiManager.js:88:19)
      at Request.self.callback (/home/sharelatex/sharelatex/web/node_modules/request/request.js:121:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/home/sharelatex/sharelatex/web/node_modules/request/request.js:978:14)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/home/sharelatex/sharelatex/web/node_modules/request/request.js:929:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickDomainCallback (node.js:492:13)
```

I've tried all suggestions on https://pt.sharelatex.com/learn/Debugging_Compilation_timeout_errors, but no success.

The weird thing is: it compiles successfully on sharelatex.com! Any idea what might be happening?

**Comment by henryoswald** [comment]
It looks like the filestore is not running, or is not accessible. Can you try a curl?

    ~ curl localhost:3009/status
    filestore sharelatex up

**Comment by dpasqualin** [comment]
Well, the user just reported that she managed to fix it. It seems to be related with a 'bad' encoding in one of the .sty files she was using. After uploading the file again the problem was solved.

Thank you and sorry to bother..
