### ISSUE TITLE
Run clsi as revice fails with 'Headers already sent'

### ISSUE THREAD

**Issue by RusAlex** [sharelatex/clsi-sharelatex#48]
```bash
echo "node /clsi-sharelatex/app.js" | sudo -i -u apache
```

then when you request a compilation of latex you see in logs

```
http.js:724
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:724:11)
    at ServerResponse.header (/clsi-sharelatex/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/clsi-sharelatex/node_modules/express/lib/response.js:164:12)
    at ServerResponse.json (/clsi-sharelatex/node_modules/express/lib/response.js:250:15)
    at ServerResponse.send (/clsi-sharelatex/node_modules/express/lib/response.js:152:21)
    at /clsi-sharelatex/app/js/CompileController.js:65:44
    at /clsi-sharelatex/app/js/CompileManager.js:177:24
    at /clsi-sharelatex/app/js/OutputCacheManager.js:127:15
    at /clsi-sharelatex/node_modules/async/lib/async.js:229:13
    at async.eachSeries (/clsi-sharelatex/node_modules/async/lib/async.js:127:20)
    at _asyncMap (/clsi-sharelatex/node_modules/async/lib/async.js:223:9)
    at Object.mapSeries (/clsi-sharelatex/node_modules/async/lib/async.js:213:23)
    at /clsi-sharelatex/app/js/OutputCacheManager.js:87:24
    at /clsi-sharelatex/node_modules/fs-extra/lib/mkdir.js:29:14
    at Object.oncomplete (fs.js:108:15)
```

**Comment by henryoswald** [comment]
are you running the docker container?

**Comment by RusAlex** [comment]
No Im not. Just Centos 6.2

**Comment by xoxys** [comment]
Does this error allready exist? I have deployed sharelatex on CentOS7 without fault.

**Comment by RusAlex** [comment]
I think I have no problems anymore. I use CLSI alot in my project. Thank you.

**Comment by BenoitTallandier** [comment]
Hi,
I have the same issue "Can't set headers after the are sent".
I installed the server on debian 8. I don't understand why I get this error, I use it in local whith ubuntu and there is no problem.
there is special manipulation to do on debian?
